version: "3.9"

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - api
    networks:
      - app-network
    restart: unless-stopped

  api:
    image: artomot/ias-diplom-api:latest
    container_name: fastapi-app
    command: uvicorn app.backend.main:app --host 0.0.0.0 --port 8000
    env_file:
      - prodv.env
    depends_on:
      - postgres
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    image: artomot/ias-diplom-frontend:latest
    container_name: nuxt-frontend
    environment:
      - NUXT_PUBLIC_API_BASE=/api
    networks:
      - app-network
    restart: unless-stopped

  postgres:
    image: postgis/postgis:17-3.4
    container_name: postgres-db
    env_file:
      - .env
    volumes:
      - pgdatata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  pgdatata:

networks:
  app-network:
    driver: bridge