// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 15.01.2026, 02:28:48
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["G:/My Programs/ias_diplom1/app/frontend/nuxt-app/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/My Programs/ias_diplom1/app/frontend/nuxt-app/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/My Programs/ias_diplom1/app/frontend/nuxt-app/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/My Programs/ias_diplom1/app/frontend/nuxt-app/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/My Programs/ias_diplom1/app/frontend/nuxt-app/app/plugins/**/*.{js,ts,mjs}","G:/My Programs/ias_diplom1/app/frontend/nuxt-app/app/composables/**/*.{js,ts,mjs}","G:/My Programs/ias_diplom1/app/frontend/nuxt-app/app/utils/**/*.{js,ts,mjs}","G:/My Programs/ias_diplom1/app/frontend/nuxt-app/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","G:/My Programs/ias_diplom1/app/frontend/nuxt-app/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","G:/My Programs/ias_diplom1/app/frontend/nuxt-app/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","G:/My Programs/ias_diplom1/app/frontend/nuxt-app/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["darkMode"] = ["selector","[class~=\"dark\"]"];;return cfg;})();

export default resolvedConfig;