"""empty message

Revision ID: 8a0291a11689
Revises: 6561aeebc3a7
Create Date: 2026-03-09 14:35:27.623174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '8a0291a11689'
down_revision: Union[str, Sequence[str], None] = '6561aeebc3a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_offer_property_type_id_property_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_seller_id_seller'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_house_material_type_id_house_material_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_land_type_id_land_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_window_view_type_id_window_view_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_gas_type_id_gas_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_sewerage_type_id_sewerage_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_heating_type_id_heating_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_renovation_type_id_renovation_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_parking_type_id_parking_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_offer_type_id_offer_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_bathroom_type_id_bathroom_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_water_supply_type_id_water_supply_type'), 'offer', type_='foreignkey')
    op.create_foreign_key(op.f('fk_offer_land_type_id_land_type'), 'offer', 'land_type', ['land_type_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_offer_seller_id_seller'), 'offer', 'seller', ['seller_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_offer_water_supply_type_id_water_supply_type'), 'offer', 'water_supply_type', ['water_supply_type_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_offer_property_type_id_property_type'), 'offer', 'property_type', ['property_type_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_offer_window_view_type_id_window_view_type'), 'offer', 'window_view_type', ['window_view_type_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_offer_sewerage_type_id_sewerage_type'), 'offer', 'sewerage_type', ['sewerage_type_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_offer_house_material_type_id_house_material_type'), 'offer', 'house_material_type', ['house_material_type_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_offer_renovation_type_id_renovation_type'), 'offer', 'renovation_type', ['renovation_type_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_offer_gas_type_id_gas_type'), 'offer', 'gas_type', ['gas_type_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_offer_offer_type_id_offer_type'), 'offer', 'offer_type', ['offer_type_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_offer_parking_type_id_parking_type'), 'offer', 'parking_type', ['parking_type_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_offer_heating_type_id_heating_type'), 'offer', 'heating_type', ['heating_type_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_offer_bathroom_type_id_bathroom_type'), 'offer', 'bathroom_type', ['bathroom_type_id'], ['id'], ondelete='SET NULL')
    op.add_column('user', sa.Column('login', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('user', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('surname', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(op.f('uq_user_login'), 'user', ['login'])
    op.drop_column('user', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('uq_user_login'), 'user', type_='unique')
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'surname')
    op.drop_column('user', 'name')
    op.drop_column('user', 'login')
    op.drop_constraint(op.f('fk_offer_bathroom_type_id_bathroom_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_heating_type_id_heating_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_parking_type_id_parking_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_offer_type_id_offer_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_gas_type_id_gas_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_renovation_type_id_renovation_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_house_material_type_id_house_material_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_sewerage_type_id_sewerage_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_window_view_type_id_window_view_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_property_type_id_property_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_water_supply_type_id_water_supply_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_seller_id_seller'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_land_type_id_land_type'), 'offer', type_='foreignkey')
    op.create_foreign_key(op.f('fk_offer_water_supply_type_id_water_supply_type'), 'offer', 'water_supply_type', ['water_supply_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_offer_bathroom_type_id_bathroom_type'), 'offer', 'bathroom_type', ['bathroom_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_offer_offer_type_id_offer_type'), 'offer', 'offer_type', ['offer_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_offer_parking_type_id_parking_type'), 'offer', 'parking_type', ['parking_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_offer_renovation_type_id_renovation_type'), 'offer', 'renovation_type', ['renovation_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_offer_heating_type_id_heating_type'), 'offer', 'heating_type', ['heating_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_offer_sewerage_type_id_sewerage_type'), 'offer', 'sewerage_type', ['sewerage_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_offer_gas_type_id_gas_type'), 'offer', 'gas_type', ['gas_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_offer_window_view_type_id_window_view_type'), 'offer', 'window_view_type', ['window_view_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_offer_land_type_id_land_type'), 'offer', 'land_type', ['land_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_offer_house_material_type_id_house_material_type'), 'offer', 'house_material_type', ['house_material_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_offer_seller_id_seller'), 'offer', 'seller', ['seller_id'], ['id'])
    op.create_foreign_key(op.f('fk_offer_property_type_id_property_type'), 'offer', 'property_type', ['property_type_id'], ['id'])
    # ### end Alembic commands ###
