"""empty message

Revision ID: 3d15d4b0a0b9
Revises: 4e721d776b3d
Create Date: 2026-03-07 12:54:04.796460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '3d15d4b0a0b9'
down_revision: Union[str, Sequence[str], None] = '4e721d776b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_password'))
    )
    op.add_column('user', sa.Column('password_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_user_password_id_password'), 'user', 'password', ['password_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_password_id_password'), 'user', type_='foreignkey')
    op.drop_column('user', 'password_id')
    op.drop_table('password')
    # ### end Alembic commands ###
