"""empty message

Revision ID: de012249563f
Revises: 6df0c348b4db
Create Date: 2026-03-07 13:42:46.017438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'de012249563f'
down_revision: Union[str, Sequence[str], None] = '6df0c348b4db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infrasturcture_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_infrasturcture_type'))
    )
    op.add_column('address', sa.Column('partnership_id', sa.Integer(), nullable=True))
    op.add_column('address', sa.Column('settlement_id', sa.Integer(), nullable=True))
    op.add_column('address', sa.Column('district_id', sa.Integer(), nullable=True))
    op.add_column('address', sa.Column('microdistrict_id', sa.Integer(), nullable=True))
    op.add_column('address', sa.Column('street_id', sa.Integer(), nullable=True))
    op.add_column('address', sa.Column('residential_complex_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_address_settlement_id_settlement'), 'address', 'settlement', ['settlement_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_address_street_id_street'), 'address', 'street', ['street_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_address_district_id_district'), 'address', 'district', ['district_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_address_partnership_id_partnership'), 'address', 'partnership', ['partnership_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_address_microdistrict_id_microdistrict'), 'address', 'microdistrict', ['microdistrict_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_address_residential_complex_id_residential_complex'), 'address', 'residential_complex', ['residential_complex_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_address_residential_complex_id_residential_complex'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_microdistrict_id_microdistrict'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_partnership_id_partnership'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_district_id_district'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_street_id_street'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_settlement_id_settlement'), 'address', type_='foreignkey')
    op.drop_column('address', 'residential_complex_id')
    op.drop_column('address', 'street_id')
    op.drop_column('address', 'microdistrict_id')
    op.drop_column('address', 'district_id')
    op.drop_column('address', 'settlement_id')
    op.drop_column('address', 'partnership_id')
    op.drop_table('infrasturcture_type')
    # ### end Alembic commands ###
