"""empty message

Revision ID: 6561aeebc3a7
Revises: de012249563f
Create Date: 2026-03-07 13:48:17.147170

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = "6561aeebc3a7"
down_revision: Union[str, Sequence[str], None] = "de012249563f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "infrastructure_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_infrastructure_type")),
    )
    op.create_table(
        "infrastructure",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "coordinates",
            geoalchemy2.types.Geography(geometry_type="POINT", srid=4326, dimension=2, from_text="ST_GeogFromText", name="geography"),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("infrastructure_type_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["infrastructure_type_id"], ["infrastructure_type.id"], name=op.f("fk_infrastructure_infrastructure_type_id_infrastructure_type")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_infrastructure")),
    )

    op.create_table(
        "address_infrastructure_link",
        sa.Column("address_id", sa.Integer(), nullable=False),
        sa.Column("infrastructure_id", sa.Integer(), nullable=False),
        sa.Column("distance", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["address_id"], ["address.id"], name=op.f("fk_address_infrastructure_link_address_id_address")),
        sa.ForeignKeyConstraint(["infrastructure_id"], ["infrastructure.id"], name=op.f("fk_address_infrastructure_link_infrastructure_id_infrastructure")),
        sa.PrimaryKeyConstraint("address_id", "infrastructure_id", name=op.f("pk_address_infrastructure_link")),
    )
    op.drop_table("infrasturcture_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "infrasturcture_type",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_infrasturcture_type")),
    )
    op.drop_table("address_infrastructure_link")

    op.drop_table("infrastructure")
    op.drop_table("infrastructure_type")
    # ### end Alembic commands ###
