"""empty message

Revision ID: 6df0c348b4db
Revises: 3d15d4b0a0b9
Create Date: 2026-03-07 13:16:28.742226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '6df0c348b4db'
down_revision: Union[str, Sequence[str], None] = '3d15d4b0a0b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('district',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_district')),
    sa.UniqueConstraint('full_name', name=op.f('uq_district_full_name'))
    )
    op.create_table('microdistrict',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_microdistrict')),
    sa.UniqueConstraint('full_name', name=op.f('uq_microdistrict_full_name'))
    )
    op.create_table('partnership_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partnership_type'))
    )
    op.create_table('residential_complex',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_suburban', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_residential_complex')),
    sa.UniqueConstraint('full_name', name=op.f('uq_residential_complex_full_name'))
    )
    op.create_table('settlement_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlement_type'))
    )
    op.create_table('street_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_street_type'))
    )
    op.create_table('partnership',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('partnership_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['partnership_type_id'], ['partnership_type.id'], name=op.f('fk_partnership_partnership_type_id_partnership_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partnership')),
    sa.UniqueConstraint('full_name', name=op.f('uq_partnership_full_name'))
    )
    op.create_table('settlement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('settlement_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['settlement_type_id'], ['settlement_type.id'], name=op.f('fk_settlement_settlement_type_id_settlement_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settlement')),
    sa.UniqueConstraint('full_name', name=op.f('uq_settlement_full_name'))
    )
    op.create_table('street',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('street_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['street_type_id'], ['street_type.id'], name=op.f('fk_street_street_type_id_street_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_street')),
    sa.UniqueConstraint('full_name', name=op.f('uq_street_full_name'))
    )
    op.drop_index(op.f('idx_address_search_vector'), table_name='address', postgresql_using='gin')
    op.create_index('ix_address_search_vector', 'address', ['search_vector'], unique=False, postgresql_using='gin')
    op.drop_constraint(op.f('uq_municipality_name'), 'municipality', type_='unique')
    op.create_unique_constraint(op.f('uq_municipality_full_name'), 'municipality', ['full_name'])
    op.drop_index(op.f('ix_municipality_type_name'), table_name='municipality_type')
    op.drop_constraint(op.f('uq_region_name'), 'region', type_='unique')
    op.create_unique_constraint(op.f('uq_region_full_name'), 'region', ['full_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_region_full_name'), 'region', type_='unique')
    op.create_unique_constraint(op.f('uq_region_name'), 'region', ['name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_municipality_type_name'), 'municipality_type', ['name'], unique=False)
    op.drop_constraint(op.f('uq_municipality_full_name'), 'municipality', type_='unique')
    op.create_unique_constraint(op.f('uq_municipality_name'), 'municipality', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_address_search_vector', table_name='address', postgresql_using='gin')
    op.create_index(op.f('idx_address_search_vector'), 'address', ['search_vector'], unique=False, postgresql_using='gin')
    op.drop_table('street')
    op.drop_table('settlement')
    op.drop_table('partnership')
    op.drop_table('street_type')
    op.drop_table('settlement_type')
    op.drop_table('residential_complex')
    op.drop_table('partnership_type')
    op.drop_table('microdistrict')
    op.drop_table('district')
    # ### end Alembic commands ###
