"""empty message

Revision ID: 322ecf271d25
Revises: ae0b1553dce4
Create Date: 2026-03-05 16:45:20.090816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '322ecf271d25'
down_revision: Union[str, Sequence[str], None] = 'ae0b1553dce4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('price_per_square_meter', sa.Integer(), nullable=True),
    sa.Column('price_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('price_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('total_area', sa.Float(), nullable=True),
    sa.Column('living_area', sa.Float(), nullable=True),
    sa.Column('kitchen_area', sa.Float(), nullable=True),
    sa.Column('land_area', sa.Float(), nullable=True),
    sa.Column('rooms_count', sa.Integer(), nullable=True),
    sa.Column('bedrooms_count', sa.Integer(), nullable=True),
    sa.Column('bathrooms_count', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('house_floors_count', sa.Integer(), nullable=True),
    sa.Column('ceiling_height', sa.Float(), nullable=True),
    sa.Column('is_new_house', sa.Boolean(), nullable=True),
    sa.Column('house_built_year', sa.Integer(), nullable=True),
    sa.Column('is_build_complete', sa.Boolean(), nullable=True),
    sa.Column('has_water_supply', sa.Boolean(), nullable=True),
    sa.Column('has_electricity', sa.Boolean(), nullable=True),
    sa.Column('has_gas', sa.Boolean(), nullable=True),
    sa.Column('has_sewerage', sa.Boolean(), nullable=True),
    sa.Column('has_heating', sa.Boolean(), nullable=True),
    sa.Column('elevators_count', sa.Integer(), nullable=True),
    sa.Column('has_elevator', sa.Boolean(), nullable=True),
    sa.Column('balconies_count', sa.Integer(), nullable=True),
    sa.Column('has_balcony', sa.Boolean(), nullable=True),
    sa.Column('has_garbage_chute', sa.Boolean(), nullable=True),
    sa.Column('has_furniture', sa.Boolean(), nullable=True),
    sa.Column('has_guard', sa.Boolean(), nullable=True),
    sa.Column('has_garage', sa.Boolean(), nullable=True),
    sa.Column('has_bathhouse', sa.Boolean(), nullable=True),
    sa.Column('has_pool', sa.Boolean(), nullable=True),
    sa.Column('has_terrace', sa.Boolean(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('images_urls', sa.ARRAY(sa.String(length=500)), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('identical_urls', sa.ARRAY(sa.String(length=500)), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('transport_access_score', sa.Float(), nullable=True),
    sa.Column('transport_access_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('elderly_score', sa.Float(), nullable=True),
    sa.Column('elderly_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('family_score', sa.Float(), nullable=True),
    sa.Column('family_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('views_count', sa.Integer(), nullable=True),
    sa.Column('daily_views_count', sa.Integer(), nullable=True),
    sa.Column('last_ten_days_views_count', sa.Integer(), nullable=True),
    sa.Column('views_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('contact_phone', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('creation_date_source', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_date_source', sa.DateTime(timezone=True), nullable=True),
    sa.Column('update_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_offer'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer')
    # ### end Alembic commands ###
