"""empty message

Revision ID: 260b9fe91a2e
Revises: af77f3f460bb
Create Date: 2026-01-13 23:47:25.824903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '260b9fe91a2e'
down_revision: Union[str, Sequence[str], None] = 'af77f3f460bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('identical_urls', sa.ARRAY(sa.String(length=500)), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'identical_urls')
    # ### end Alembic commands ###
