"""empty message

Revision ID: 55ceff1d9d17
Revises: 5d094afd9eb4
Create Date: 2026-01-28 13:56:18.305907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '55ceff1d9d17'
down_revision: Union[str, Sequence[str], None] = '5d094afd9eb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_address_district_id'), 'address', ['district_id'], unique=False)
    op.create_index(op.f('ix_district_short_name'), 'district', ['short_name'], unique=False)
    op.create_index(op.f('ix_microdistrict_short_name'), 'microdistrict', ['short_name'], unique=False)
    op.create_index(op.f('ix_municipality_type_name'), 'municipality_type', ['name'], unique=False)
    op.create_index(op.f('ix_offer_address_id'), 'offer', ['address_id'], unique=False)
    op.create_index(op.f('ix_settlement_short_name'), 'settlement', ['short_name'], unique=False)
    op.create_index(op.f('ix_street_short_name'), 'street', ['short_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_street_short_name'), table_name='street')
    op.drop_index(op.f('ix_settlement_short_name'), table_name='settlement')
    op.drop_index(op.f('ix_offer_address_id'), table_name='offer')
    op.drop_index(op.f('ix_municipality_type_name'), table_name='municipality_type')
    op.drop_index(op.f('ix_microdistrict_short_name'), table_name='microdistrict')
    op.drop_index(op.f('ix_district_short_name'), table_name='district')
    op.drop_index(op.f('ix_address_district_id'), table_name='address')
    # ### end Alembic commands ###
