"""empty message

Revision ID: 5d094afd9eb4
Revises: f18bb9693637
Create Date: 2026-01-26 23:03:11.551519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5d094afd9eb4'
down_revision: Union[str, Sequence[str], None] = 'f18bb9693637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_user_name'), 'user', type_='unique')
    op.create_unique_constraint(op.f('uq_user_email'), 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_email'), 'user', type_='unique')
    op.create_unique_constraint(op.f('uq_user_user_name'), 'user', ['user_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
