"""empty message

Revision ID: 5e63bafbcf06
Revises:
Create Date: 2025-12-19 20:48:52.949054

"""

from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e63bafbcf06"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bathroom_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bathroom_type")),
    )
    op.create_table(
        "district",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("short_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_district")),
        sa.UniqueConstraint("name", name=op.f("uq_district_name")),
    )
    op.create_index(op.f("ix_district_short_name"), "district", ["short_name"], unique=False)
    op.create_table(
        "gas_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gas_type")),
    )
    op.create_table(
        "heating_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_heating_type")),
    )
    op.create_table(
        "house_material_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_house_material_type")),
    )
    op.create_table(
        "infrastructure_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_infrastructure_type")),
    )
    op.create_table(
        "land_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_land_type")),
    )
    op.create_table(
        "microdistrict",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("short_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_microdistrict")),
        sa.UniqueConstraint("name", name=op.f("uq_microdistrict_name")),
    )
    op.create_table(
        "municipality_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_municipality_type")),
    )
    op.create_table(
        "offer_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offer_type")),
    )
    op.create_table(
        "parking_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_parking_type")),
    )
    op.create_table(
        "partnership_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_partnership_type")),
    )
    op.create_table(
        "password",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password")),
    )
    op.create_table(
        "property_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_property_type")),
    )
    op.create_table(
        "region",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("short_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_region")),
        sa.UniqueConstraint("name", name=op.f("uq_region_name")),
    )
    op.create_index(op.f("ix_region_short_name"), "region", ["short_name"], unique=False)
    op.create_table(
        "renovation_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_renovation_type")),
    )
    op.create_table(
        "residential_complex",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("short_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_suburban", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_residential_complex")),
        sa.UniqueConstraint("name", name=op.f("uq_residential_complex_name")),
    )
    op.create_index(op.f("ix_residential_complex_short_name"), "residential_complex", ["short_name"], unique=False)
    op.create_table(
        "role",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role")),
        sa.UniqueConstraint("name", name=op.f("uq_role_name")),
    )
    op.create_table(
        "seller_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seller_type")),
    )
    op.create_table(
        "settlement_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settlement_type")),
    )
    op.create_table(
        "sewerage_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sewerage_type")),
    )
    op.create_table(
        "street_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_street_type")),
    )
    op.create_table(
        "water_supply_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_water_supply_type")),
    )
    op.create_table(
        "window_view_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_window_view_type")),
    )
    op.create_table(
        "infrastructure",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("coordinates", geoalchemy2.types.Geography(geometry_type="POINT", srid=4326, dimension=2, from_text="ST_GeogFromText", name="geography"), nullable=True),
        sa.Column("infrastructure_type_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["infrastructure_type_id"], ["infrastructure_type.id"], name=op.f("fk_infrastructure_infrastructure_type_id_infrastructure_type")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_infrastructure")),
        sa.UniqueConstraint("name", "coordinates", name="uq_infrastructure_name_coordinates"),
    )

    op.create_table(
        "municipality",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("short_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("municipality_type_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["municipality_type_id"], ["municipality_type.id"], name=op.f("fk_municipality_municipality_type_id_municipality_type")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_municipality")),
        sa.UniqueConstraint("name", name=op.f("uq_municipality_name")),
    )
    op.create_table(
        "partnership",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("short_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("partnership_type_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["partnership_type_id"], ["partnership_type.id"], name=op.f("fk_partnership_partnership_type_id_partnership_type")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_partnership")),
        sa.UniqueConstraint("name", name=op.f("uq_partnership_name")),
    )
    op.create_table(
        "seller",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("rating", sa.Float(), nullable=True),
        sa.Column("foundation_date", sa.Integer(), nullable=True),
        sa.Column("seller_type_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["seller_type_id"], ["seller_type.id"], name=op.f("fk_seller_seller_type_id_seller_type")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seller")),
        sa.UniqueConstraint("name", name=op.f("uq_seller_name")),
    )
    op.create_table(
        "settlement",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("short_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("settlement_type_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["settlement_type_id"], ["settlement_type.id"], name=op.f("fk_settlement_settlement_type_id_settlement_type")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settlement")),
        sa.UniqueConstraint("full_name", name=op.f("uq_settlement_full_name")),
    )
    op.create_index(op.f("ix_settlement_short_name"), "settlement", ["short_name"], unique=False)
    op.create_table(
        "street",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("short_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("street_type_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["street_type_id"], ["street_type.id"], name=op.f("fk_street_street_type_id_street_type")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_street")),
        sa.UniqueConstraint("name", name=op.f("uq_street_name")),
    )
    op.create_index(op.f("ix_street_short_name"), "street", ["short_name"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("registration_date", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.Column("password_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["password_id"], ["password.id"], name=op.f("fk_user_password_id_password")),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], name=op.f("fk_user_role_id_role")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("user_name", name=op.f("uq_user_user_name")),
    )
    op.create_table(
        "address",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("house_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("full_address", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True),
        sa.Column("coordinates", geoalchemy2.types.Geography(geometry_type="POINT", srid=4326, dimension=2, from_text="ST_GeogFromText", name="geography"), nullable=True),
        sa.Column("region_id", sa.Integer(), nullable=True),
        sa.Column("municipality_id", sa.Integer(), nullable=True),
        sa.Column("settlement_id", sa.Integer(), nullable=True),
        sa.Column("partnership_id", sa.Integer(), nullable=True),
        sa.Column("district_id", sa.Integer(), nullable=True),
        sa.Column("microdistrict_id", sa.Integer(), nullable=True),
        sa.Column("street_id", sa.Integer(), nullable=True),
        sa.Column("residential_complex_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["district_id"], ["district.id"], name=op.f("fk_address_district_id_district")),
        sa.ForeignKeyConstraint(["microdistrict_id"], ["microdistrict.id"], name=op.f("fk_address_microdistrict_id_microdistrict")),
        sa.ForeignKeyConstraint(["municipality_id"], ["municipality.id"], name=op.f("fk_address_municipality_id_municipality"), ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["partnership_id"], ["partnership.id"], name=op.f("fk_address_partnership_id_partnership")),
        sa.ForeignKeyConstraint(["region_id"], ["region.id"], name=op.f("fk_address_region_id_region")),
        sa.ForeignKeyConstraint(["residential_complex_id"], ["residential_complex.id"], name=op.f("fk_address_residential_complex_id_residential_complex")),
        sa.ForeignKeyConstraint(["settlement_id"], ["settlement.id"], name=op.f("fk_address_settlement_id_settlement"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["street_id"], ["street.id"], name=op.f("fk_address_street_id_street")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_address")),
        sa.UniqueConstraint("coordinates", name=op.f("uq_address_coordinates")),
    )

    op.create_index("idx_address_search_vector", "address", ["search_vector"], unique=False, postgresql_using="gin")
    op.create_index(op.f("ix_address_district_id"), "address", ["district_id"], unique=False)
    op.create_index(op.f("ix_address_full_address"), "address", ["full_address"], unique=False)
    op.create_index(op.f("ix_address_microdistrict_id"), "address", ["microdistrict_id"], unique=False)
    op.create_index(op.f("ix_address_municipality_id"), "address", ["municipality_id"], unique=False)
    op.create_index(op.f("ix_address_partnership_id"), "address", ["partnership_id"], unique=False)
    op.create_index(op.f("ix_address_region_id"), "address", ["region_id"], unique=False)
    op.create_index(op.f("ix_address_settlement_id"), "address", ["settlement_id"], unique=False)
    op.create_index(op.f("ix_address_street_id"), "address", ["street_id"], unique=False)
    op.create_table(
        "address_infrastructure_link",
        sa.Column("infrastructure_id", sa.Integer(), nullable=False),
        sa.Column("address_id", sa.Integer(), nullable=False),
        sa.Column("distance", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["address_id"], ["address.id"], name=op.f("fk_address_infrastructure_link_address_id_address"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["infrastructure_id"], ["infrastructure.id"], name=op.f("fk_address_infrastructure_link_infrastructure_id_infrastructure"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("infrastructure_id", "address_id", name=op.f("pk_address_infrastructure_link")),
    )
    op.create_index(op.f("ix_address_infrastructure_link_address_id"), "address_infrastructure_link", ["address_id"], unique=False)
    op.create_index(op.f("ix_address_infrastructure_link_infrastructure_id"), "address_infrastructure_link", ["infrastructure_id"], unique=False)
    op.create_table(
        "offer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("price_per_square_meter", sa.Integer(), nullable=True),
        sa.Column("price_category", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("price_history", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("total_area", sa.Float(), nullable=True),
        sa.Column("living_area", sa.Float(), nullable=True),
        sa.Column("kitchen_area", sa.Float(), nullable=True),
        sa.Column("land_area", sa.Float(), nullable=True),
        sa.Column("rooms_count", sa.Integer(), nullable=True),
        sa.Column("bedrooms_count", sa.Integer(), nullable=True),
        sa.Column("bathrooms_count", sa.Integer(), nullable=True),
        sa.Column("floor", sa.Integer(), nullable=True),
        sa.Column("house_floors_count", sa.Integer(), nullable=True),
        sa.Column("ceiling_height", sa.Float(), nullable=True),
        sa.Column("is_new_house", sa.Boolean(), nullable=True),
        sa.Column("house_built_year", sa.Integer(), nullable=True),
        sa.Column("is_build_complete", sa.Boolean(), nullable=True),
        sa.Column("has_water_supply", sa.Boolean(), nullable=True),
        sa.Column("has_electricity", sa.Boolean(), nullable=True),
        sa.Column("has_gas", sa.Boolean(), nullable=True),
        sa.Column("has_sewerage", sa.Boolean(), nullable=True),
        sa.Column("has_heating", sa.Boolean(), nullable=True),
        sa.Column("elevators_count", sa.Integer(), nullable=True),
        sa.Column("has_elevator", sa.Boolean(), nullable=True),
        sa.Column("balconies_count", sa.Integer(), nullable=True),
        sa.Column("has_balcony", sa.Boolean(), nullable=True),
        sa.Column("has_garbage_chute", sa.Boolean(), nullable=True),
        sa.Column("has_furniture", sa.Boolean(), nullable=True),
        sa.Column("has_guard", sa.Boolean(), nullable=True),
        sa.Column("has_garage", sa.Boolean(), nullable=True),
        sa.Column("has_bathhouse", sa.Boolean(), nullable=True),
        sa.Column("has_pool", sa.Boolean(), nullable=True),
        sa.Column("has_terrace", sa.Boolean(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("images_urls", sa.ARRAY(sa.String(length=500)), nullable=True),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("transport_access_score", sa.Float(), nullable=True),
        sa.Column("transport_access_category", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("elderly_score", sa.Float(), nullable=True),
        sa.Column("elderly_category", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("family_score", sa.Float(), nullable=True),
        sa.Column("family_category", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("views_count", sa.Integer(), nullable=True),
        sa.Column("daily_views_count", sa.Integer(), nullable=True),
        sa.Column("last_ten_days_views_count", sa.Integer(), nullable=True),
        sa.Column("views_history", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("contact_phone", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("creation_date_source", sa.DateTime(timezone=True), nullable=True),
        sa.Column("update_date_source", sa.DateTime(timezone=True), nullable=True),
        sa.Column("update_date", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("address_id", sa.Integer(), nullable=True),
        sa.Column("seller_id", sa.Integer(), nullable=True),
        sa.Column("offer_type_id", sa.Integer(), nullable=True),
        sa.Column("property_type_id", sa.Integer(), nullable=True),
        sa.Column("land_type_id", sa.Integer(), nullable=True),
        sa.Column("bathroom_type_id", sa.Integer(), nullable=True),
        sa.Column("renovation_type_id", sa.Integer(), nullable=True),
        sa.Column("window_view_type_id", sa.Integer(), nullable=True),
        sa.Column("parking_type_id", sa.Integer(), nullable=True),
        sa.Column("house_material_type_id", sa.Integer(), nullable=True),
        sa.Column("heating_type_id", sa.Integer(), nullable=True),
        sa.Column("gas_type_id", sa.Integer(), nullable=True),
        sa.Column("sewerage_type_id", sa.Integer(), nullable=True),
        sa.Column("water_supply_type_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["address_id"], ["address.id"], name=op.f("fk_offer_address_id_address"), ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["bathroom_type_id"], ["bathroom_type.id"], name=op.f("fk_offer_bathroom_type_id_bathroom_type")),
        sa.ForeignKeyConstraint(["gas_type_id"], ["gas_type.id"], name=op.f("fk_offer_gas_type_id_gas_type")),
        sa.ForeignKeyConstraint(["heating_type_id"], ["heating_type.id"], name=op.f("fk_offer_heating_type_id_heating_type")),
        sa.ForeignKeyConstraint(["house_material_type_id"], ["house_material_type.id"], name=op.f("fk_offer_house_material_type_id_house_material_type")),
        sa.ForeignKeyConstraint(["land_type_id"], ["land_type.id"], name=op.f("fk_offer_land_type_id_land_type")),
        sa.ForeignKeyConstraint(["offer_type_id"], ["offer_type.id"], name=op.f("fk_offer_offer_type_id_offer_type")),
        sa.ForeignKeyConstraint(["parking_type_id"], ["parking_type.id"], name=op.f("fk_offer_parking_type_id_parking_type")),
        sa.ForeignKeyConstraint(["property_type_id"], ["property_type.id"], name=op.f("fk_offer_property_type_id_property_type")),
        sa.ForeignKeyConstraint(["renovation_type_id"], ["renovation_type.id"], name=op.f("fk_offer_renovation_type_id_renovation_type")),
        sa.ForeignKeyConstraint(["seller_id"], ["seller.id"], name=op.f("fk_offer_seller_id_seller")),
        sa.ForeignKeyConstraint(["sewerage_type_id"], ["sewerage_type.id"], name=op.f("fk_offer_sewerage_type_id_sewerage_type")),
        sa.ForeignKeyConstraint(["water_supply_type_id"], ["water_supply_type.id"], name=op.f("fk_offer_water_supply_type_id_water_supply_type")),
        sa.ForeignKeyConstraint(["window_view_type_id"], ["window_view_type.id"], name=op.f("fk_offer_window_view_type_id_window_view_type")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offer")),
    )
    op.create_index(op.f("ix_offer_price"), "offer", ["price"], unique=False)
    op.create_index(op.f("ix_offer_price_category"), "offer", ["price_category"], unique=False)
    op.create_index(op.f("ix_offer_price_per_square_meter"), "offer", ["price_per_square_meter"], unique=False)
    op.create_index(op.f("ix_offer_url"), "offer", ["url"], unique=False)
    op.create_table(
        "favorite",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("offer_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["offer_id"], ["offer.id"], name=op.f("fk_favorite_offer_id_offer")),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name=op.f("fk_favorite_user_id_user")),
        sa.PrimaryKeyConstraint("user_id", "offer_id", name=op.f("pk_favorite")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("favorite")
    op.drop_index(op.f("ix_offer_url"), table_name="offer")
    op.drop_index(op.f("ix_offer_price_per_square_meter"), table_name="offer")
    op.drop_index(op.f("ix_offer_price_category"), table_name="offer")
    op.drop_index(op.f("ix_offer_price"), table_name="offer")
    op.drop_table("offer")
    op.drop_index(op.f("ix_address_infrastructure_link_infrastructure_id"), table_name="address_infrastructure_link")
    op.drop_index(op.f("ix_address_infrastructure_link_address_id"), table_name="address_infrastructure_link")
    op.drop_table("address_infrastructure_link")
    op.drop_index(op.f("ix_address_street_id"), table_name="address")
    op.drop_index(op.f("ix_address_settlement_id"), table_name="address")
    op.drop_index(op.f("ix_address_region_id"), table_name="address")
    op.drop_index(op.f("ix_address_partnership_id"), table_name="address")
    op.drop_index(op.f("ix_address_municipality_id"), table_name="address")
    op.drop_index(op.f("ix_address_microdistrict_id"), table_name="address")
    op.drop_index(op.f("ix_address_full_address"), table_name="address")
    op.drop_index(op.f("ix_address_district_id"), table_name="address")
    op.drop_index("idx_address_search_vector", table_name="address", postgresql_using="gin")
    op.drop_index("idx_address_coordinates", table_name="address", postgresql_using="gist")
    op.drop_table("address")
    op.drop_table("user")
    op.drop_index(op.f("ix_street_short_name"), table_name="street")
    op.drop_table("street")
    op.drop_index(op.f("ix_settlement_short_name"), table_name="settlement")
    op.drop_table("settlement")
    op.drop_table("seller")
    op.drop_table("partnership")
    op.drop_table("municipality")
    op.drop_index("idx_infrastructure_coordinates", table_name="infrastructure", postgresql_using="gist")
    op.drop_table("infrastructure")
    op.drop_table("window_view_type")
    op.drop_table("water_supply_type")
    op.drop_table("street_type")
    op.drop_table("sewerage_type")
    op.drop_table("settlement_type")
    op.drop_table("seller_type")
    op.drop_table("role")
    op.drop_index(op.f("ix_residential_complex_short_name"), table_name="residential_complex")
    op.drop_table("residential_complex")
    op.drop_table("renovation_type")
    op.drop_index(op.f("ix_region_short_name"), table_name="region")
    op.drop_table("region")
    op.drop_table("property_type")
    op.drop_table("password")
    op.drop_table("partnership_type")
    op.drop_table("parking_type")
    op.drop_table("offer_type")
    op.drop_table("municipality_type")
    op.drop_table("microdistrict")
    op.drop_table("land_type")
    op.drop_table("infrastructure_type")
    op.drop_table("house_material_type")
    op.drop_table("heating_type")
    op.drop_table("gas_type")
    op.drop_index(op.f("ix_district_short_name"), table_name="district")
    op.drop_table("district")
    op.drop_table("bathroom_type")
    # ### end Alembic commands ###
    # ### end Alembic commands ###
    # ### end Alembic commands ###
