"""empty message

Revision ID: 62a9a63afa86
Revises: 55ceff1d9d17
Create Date: 2026-02-05 00:53:37.959740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '62a9a63afa86'
down_revision: Union[str, Sequence[str], None] = '55ceff1d9d17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_address_residential_complex_id_residential_complex'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_municipality_id_municipality'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_partnership_id_partnership'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_district_id_district'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_settlement_id_settlement'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_microdistrict_id_microdistrict'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_region_id_region'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_super_municipality_id_super_municipality'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_street_id_street'), 'address', type_='foreignkey')
    op.create_foreign_key(op.f('fk_address_partnership_id_partnership'), 'address', 'partnership', ['partnership_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_address_settlement_id_settlement'), 'address', 'settlement', ['settlement_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_address_super_municipality_id_super_municipality'), 'address', 'super_municipality', ['super_municipality_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_address_residential_complex_id_residential_complex'), 'address', 'residential_complex', ['residential_complex_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_address_street_id_street'), 'address', 'street', ['street_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_address_region_id_region'), 'address', 'region', ['region_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_address_district_id_district'), 'address', 'district', ['district_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_address_municipality_id_municipality'), 'address', 'municipality', ['municipality_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_address_microdistrict_id_microdistrict'), 'address', 'microdistrict', ['microdistrict_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_address_microdistrict_id_microdistrict'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_municipality_id_municipality'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_district_id_district'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_region_id_region'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_street_id_street'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_residential_complex_id_residential_complex'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_super_municipality_id_super_municipality'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_settlement_id_settlement'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_partnership_id_partnership'), 'address', type_='foreignkey')
    op.create_foreign_key(op.f('fk_address_street_id_street'), 'address', 'street', ['street_id'], ['id'])
    op.create_foreign_key(op.f('fk_address_super_municipality_id_super_municipality'), 'address', 'super_municipality', ['super_municipality_id'], ['id'])
    op.create_foreign_key(op.f('fk_address_region_id_region'), 'address', 'region', ['region_id'], ['id'])
    op.create_foreign_key(op.f('fk_address_microdistrict_id_microdistrict'), 'address', 'microdistrict', ['microdistrict_id'], ['id'])
    op.create_foreign_key(op.f('fk_address_settlement_id_settlement'), 'address', 'settlement', ['settlement_id'], ['id'])
    op.create_foreign_key(op.f('fk_address_district_id_district'), 'address', 'district', ['district_id'], ['id'])
    op.create_foreign_key(op.f('fk_address_partnership_id_partnership'), 'address', 'partnership', ['partnership_id'], ['id'])
    op.create_foreign_key(op.f('fk_address_municipality_id_municipality'), 'address', 'municipality', ['municipality_id'], ['id'])
    op.create_foreign_key(op.f('fk_address_residential_complex_id_residential_complex'), 'address', 'residential_complex', ['residential_complex_id'], ['id'])
    # ### end Alembic commands ###
