"""empty message

Revision ID: 679c295fa3b2
Revises: cb68faf10a79
Create Date: 2026-01-17 16:01:48.319102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '679c295fa3b2'
down_revision: Union[str, Sequence[str], None] = 'cb68faf10a79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_address_settlement_id_settlement'), 'address', type_='foreignkey')
    op.create_foreign_key(op.f('fk_address_settlement_id_settlement'), 'address', 'settlement', ['settlement_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_address_settlement_id_settlement'), 'address', type_='foreignkey')
    op.create_foreign_key(op.f('fk_address_settlement_id_settlement'), 'address', 'settlement', ['settlement_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
