"""empty message

Revision ID: af77f3f460bb
Revises: b19acdc5ecc5
Create Date: 2026-01-09 18:47:29.262409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'af77f3f460bb'
down_revision: Union[str, Sequence[str], None] = 'b19acdc5ecc5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('fk_address_partnership_id_partnership'), 'address', 'partnership', ['partnership_id'], ['id'])
    op.create_foreign_key(op.f('fk_address_settlement_id_settlement'), 'address', 'settlement', ['settlement_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_address_municipality_id_municipality'), 'address', 'municipality', ['municipality_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_address_microdistrict_id_microdistrict'), 'address', 'microdistrict', ['microdistrict_id'], ['id'])
    op.create_foreign_key(op.f('fk_address_district_id_district'), 'address', 'district', ['district_id'], ['id'])
    op.create_foreign_key(op.f('fk_address_region_id_region'), 'address', 'region', ['region_id'], ['id'])
    op.create_foreign_key(op.f('fk_address_street_id_street'), 'address', 'street', ['street_id'], ['id'])
    op.create_foreign_key(op.f('fk_address_residential_complex_id_residential_complex'), 'address', 'residential_complex', ['residential_complex_id'], ['id'])
    op.create_foreign_key(op.f('fk_address_infrastructure_link_infrastructure_id_infrastructure'), 'address_infrastructure_link', 'infrastructure', ['infrastructure_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_address_infrastructure_link_address_id_address'), 'address_infrastructure_link', 'address', ['address_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_favorite_offer_id_offer'), 'favorite', 'offer', ['offer_id'], ['id'])
    op.create_foreign_key(op.f('fk_favorite_user_id_user'), 'favorite', 'user', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_infrastructure_infrastructure_type_id_infrastructure_type'), 'infrastructure', 'infrastructure_type', ['infrastructure_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_municipality_municipality_type_id_municipality_type'), 'municipality', 'municipality_type', ['municipality_type_id'], ['id'])
    op.add_column('offer', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(op.f('fk_offer_heating_type_id_heating_type'), 'offer', 'heating_type', ['heating_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_offer_offer_type_id_offer_type'), 'offer', 'offer_type', ['offer_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_offer_renovation_type_id_renovation_type'), 'offer', 'renovation_type', ['renovation_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_offer_seller_id_seller'), 'offer', 'seller', ['seller_id'], ['id'])
    op.create_foreign_key(op.f('fk_offer_address_id_address'), 'offer', 'address', ['address_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_offer_land_type_id_land_type'), 'offer', 'land_type', ['land_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_offer_house_material_type_id_house_material_type'), 'offer', 'house_material_type', ['house_material_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_offer_gas_type_id_gas_type'), 'offer', 'gas_type', ['gas_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_offer_bathroom_type_id_bathroom_type'), 'offer', 'bathroom_type', ['bathroom_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_offer_property_type_id_property_type'), 'offer', 'property_type', ['property_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_offer_sewerage_type_id_sewerage_type'), 'offer', 'sewerage_type', ['sewerage_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_offer_window_view_type_id_window_view_type'), 'offer', 'window_view_type', ['window_view_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_offer_parking_type_id_parking_type'), 'offer', 'parking_type', ['parking_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_offer_water_supply_type_id_water_supply_type'), 'offer', 'water_supply_type', ['water_supply_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_partnership_partnership_type_id_partnership_type'), 'partnership', 'partnership_type', ['partnership_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_seller_seller_type_id_seller_type'), 'seller', 'seller_type', ['seller_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_settlement_settlement_type_id_settlement_type'), 'settlement', 'settlement_type', ['settlement_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_street_street_type_id_street_type'), 'street', 'street_type', ['street_type_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_password_id_password'), 'user', 'password', ['password_id'], ['id'])
    op.create_foreign_key(op.f('fk_user_role_id_role'), 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_role_id_role'), 'user', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_password_id_password'), 'user', type_='foreignkey')
    op.drop_constraint(op.f('fk_street_street_type_id_street_type'), 'street', type_='foreignkey')
    op.drop_constraint(op.f('fk_settlement_settlement_type_id_settlement_type'), 'settlement', type_='foreignkey')
    op.drop_constraint(op.f('fk_seller_seller_type_id_seller_type'), 'seller', type_='foreignkey')
    op.drop_constraint(op.f('fk_partnership_partnership_type_id_partnership_type'), 'partnership', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_water_supply_type_id_water_supply_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_parking_type_id_parking_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_window_view_type_id_window_view_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_sewerage_type_id_sewerage_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_property_type_id_property_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_bathroom_type_id_bathroom_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_gas_type_id_gas_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_house_material_type_id_house_material_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_land_type_id_land_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_address_id_address'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_seller_id_seller'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_renovation_type_id_renovation_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_offer_type_id_offer_type'), 'offer', type_='foreignkey')
    op.drop_constraint(op.f('fk_offer_heating_type_id_heating_type'), 'offer', type_='foreignkey')
    op.drop_column('offer', 'source')
    op.drop_constraint(op.f('fk_municipality_municipality_type_id_municipality_type'), 'municipality', type_='foreignkey')
    op.drop_constraint(op.f('fk_infrastructure_infrastructure_type_id_infrastructure_type'), 'infrastructure', type_='foreignkey')
    op.drop_constraint(op.f('fk_favorite_user_id_user'), 'favorite', type_='foreignkey')
    op.drop_constraint(op.f('fk_favorite_offer_id_offer'), 'favorite', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_infrastructure_link_address_id_address'), 'address_infrastructure_link', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_infrastructure_link_infrastructure_id_infrastructure'), 'address_infrastructure_link', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_residential_complex_id_residential_complex'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_street_id_street'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_region_id_region'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_district_id_district'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_microdistrict_id_microdistrict'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_municipality_id_municipality'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_settlement_id_settlement'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_partnership_id_partnership'), 'address', type_='foreignkey')
    # ### end Alembic commands ###
