"""empty message

Revision ID: bf1f2e130a77
Revises: 260b9fe91a2e
Create Date: 2026-01-14 13:00:18.856362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bf1f2e130a77'
down_revision: Union[str, Sequence[str], None] = '260b9fe91a2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_offer_is_active'), 'offer', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_offer_is_active'), table_name='offer')
    op.drop_column('offer', 'is_active')
    # ### end Alembic commands ###
