"""empty message

Revision ID: c3d4e46fd05f
Revises: 679c295fa3b2
Create Date: 2026-01-20 22:46:48.706361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c3d4e46fd05f'
down_revision: Union[str, Sequence[str], None] = '679c295fa3b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('address_idx_region_id'), table_name='address')
    op.drop_index(op.f('district_idx_short_name_id'), table_name='district')
    op.drop_index(op.f('microdistrict_idx_id'), table_name='microdistrict')
    op.drop_index(op.f('idx_offer_price_category'), table_name='offer')
    op.drop_index(op.f('idx_offer_views_history_array'), table_name='offer', postgresql_using='gin', postgresql_where="(jsonb_typeof(views_history) = 'array'::text)")
    op.drop_index(op.f('offer_idx_address_id_total_area_price'), table_name='offer')
    op.drop_index(op.f('region_idx_short_name'), table_name='region')
    op.drop_index(op.f('settlement_idx_short_name_id'), table_name='settlement')
    op.drop_index(op.f('settlement_type_idx_id'), table_name='settlement_type')
    op.drop_index(op.f('street_idx_id_short_name'), table_name='street')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('street_idx_id_short_name'), 'street', ['id', 'short_name'], unique=False)
    op.create_index(op.f('settlement_type_idx_id'), 'settlement_type', ['id'], unique=False)
    op.create_index(op.f('settlement_idx_short_name_id'), 'settlement', ['short_name', 'id'], unique=False)
    op.create_index(op.f('region_idx_short_name'), 'region', ['short_name'], unique=False)
    op.create_index(op.f('offer_idx_address_id_total_area_price'), 'offer', ['address_id', 'total_area', 'price'], unique=False)
    op.create_index(op.f('idx_offer_views_history_array'), 'offer', ['views_history'], unique=False, postgresql_using='gin', postgresql_where="(jsonb_typeof(views_history) = 'array'::text)")
    op.create_index(op.f('idx_offer_price_category'), 'offer', ['price_category'], unique=False)
    op.create_index(op.f('microdistrict_idx_id'), 'microdistrict', ['id'], unique=False)
    op.create_index(op.f('district_idx_short_name_id'), 'district', ['short_name', 'id'], unique=False)
    op.create_index(op.f('address_idx_region_id'), 'address', ['region_id'], unique=False)
    # ### end Alembic commands ###
