"""empty message

Revision ID: da9c59c77c8d
Revises: c3d4e46fd05f
Create Date: 2026-01-20 23:31:48.223201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'da9c59c77c8d'
down_revision: Union[str, Sequence[str], None] = 'c3d4e46fd05f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('super_municipality_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_super_municipality_type'))
    )
    op.create_table('super_municipality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('short_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('super_municipality_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['super_municipality_type_id'], ['super_municipality_type.id'], name=op.f('fk_super_municipality_super_municipality_type_id_super_municipality_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_super_municipality')),
    sa.UniqueConstraint('name', name=op.f('uq_super_municipality_name'))
    )
    op.add_column('address', sa.Column('super_municipality_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_address_district_id'), table_name='address')
    op.drop_index(op.f('ix_address_full_address'), table_name='address')
    op.drop_index(op.f('ix_address_microdistrict_id'), table_name='address')
    op.drop_index(op.f('ix_address_municipality_id'), table_name='address')
    op.drop_index(op.f('ix_address_partnership_id'), table_name='address')
    op.drop_index(op.f('ix_address_region_id'), table_name='address')
    op.drop_index(op.f('ix_address_settlement_id'), table_name='address')
    op.drop_index(op.f('ix_address_street_id'), table_name='address')
    op.drop_constraint(op.f('fk_address_municipality_id_municipality'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_settlement_id_settlement'), 'address', type_='foreignkey')
    op.create_foreign_key(op.f('fk_address_super_municipality_id_super_municipality'), 'address', 'super_municipality', ['super_municipality_id'], ['id'])
    op.create_foreign_key(op.f('fk_address_municipality_id_municipality'), 'address', 'municipality', ['municipality_id'], ['id'])
    op.create_foreign_key(op.f('fk_address_settlement_id_settlement'), 'address', 'settlement', ['settlement_id'], ['id'])
    op.drop_index(op.f('ix_address_infrastructure_link_address_id'), table_name='address_infrastructure_link')
    op.drop_index(op.f('ix_address_infrastructure_link_infrastructure_id'), table_name='address_infrastructure_link')
    op.drop_index(op.f('ix_district_short_name'), table_name='district')
    op.drop_index(op.f('ix_offer_is_active'), table_name='offer')
    op.drop_index(op.f('ix_offer_price'), table_name='offer')
    op.drop_index(op.f('ix_offer_price_category'), table_name='offer')
    op.drop_index(op.f('ix_offer_price_per_square_meter'), table_name='offer')
    op.drop_index(op.f('ix_offer_url'), table_name='offer')
    op.drop_index(op.f('ix_region_short_name'), table_name='region')
    op.drop_index(op.f('ix_residential_complex_short_name'), table_name='residential_complex')
    op.drop_index(op.f('ix_settlement_short_name'), table_name='settlement')
    op.drop_index(op.f('ix_street_short_name'), table_name='street')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_street_short_name'), 'street', ['short_name'], unique=False)
    op.create_index(op.f('ix_settlement_short_name'), 'settlement', ['short_name'], unique=False)
    op.create_index(op.f('ix_residential_complex_short_name'), 'residential_complex', ['short_name'], unique=False)
    op.create_index(op.f('ix_region_short_name'), 'region', ['short_name'], unique=False)
    op.create_index(op.f('ix_offer_url'), 'offer', ['url'], unique=False)
    op.create_index(op.f('ix_offer_price_per_square_meter'), 'offer', ['price_per_square_meter'], unique=False)
    op.create_index(op.f('ix_offer_price_category'), 'offer', ['price_category'], unique=False)
    op.create_index(op.f('ix_offer_price'), 'offer', ['price'], unique=False)
    op.create_index(op.f('ix_offer_is_active'), 'offer', ['is_active'], unique=False)
    op.create_index(op.f('ix_district_short_name'), 'district', ['short_name'], unique=False)
    op.create_index(op.f('ix_address_infrastructure_link_infrastructure_id'), 'address_infrastructure_link', ['infrastructure_id'], unique=False)
    op.create_index(op.f('ix_address_infrastructure_link_address_id'), 'address_infrastructure_link', ['address_id'], unique=False)
    op.drop_constraint(op.f('fk_address_settlement_id_settlement'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_municipality_id_municipality'), 'address', type_='foreignkey')
    op.drop_constraint(op.f('fk_address_super_municipality_id_super_municipality'), 'address', type_='foreignkey')
    op.create_foreign_key(op.f('fk_address_settlement_id_settlement'), 'address', 'settlement', ['settlement_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_address_municipality_id_municipality'), 'address', 'municipality', ['municipality_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_address_street_id'), 'address', ['street_id'], unique=False)
    op.create_index(op.f('ix_address_settlement_id'), 'address', ['settlement_id'], unique=False)
    op.create_index(op.f('ix_address_region_id'), 'address', ['region_id'], unique=False)
    op.create_index(op.f('ix_address_partnership_id'), 'address', ['partnership_id'], unique=False)
    op.create_index(op.f('ix_address_municipality_id'), 'address', ['municipality_id'], unique=False)
    op.create_index(op.f('ix_address_microdistrict_id'), 'address', ['microdistrict_id'], unique=False)
    op.create_index(op.f('ix_address_full_address'), 'address', ['full_address'], unique=False)
    op.create_index(op.f('ix_address_district_id'), 'address', ['district_id'], unique=False)
    op.drop_column('address', 'super_municipality_id')
    op.drop_table('super_municipality')
    op.drop_table('super_municipality_type')
    # ### end Alembic commands ###
