[avito]
url = "https://www.avito.ru"
url_api = "https://www.avito.ru/web/1/js/items?s=104&params[201]=1059"
selector = "pre"
regex_selector = "isVerifiedItem\".*?urlPath\":\"([^\"]+)"
max_page = 101

[cian]
url = "https://www.cian.ru"
url_api = "https://cian.ru/cat.php?deal_type=sale&engine_version=2&sort=creation_date_asc"
selector = "[data-name=\"Offers\"]"
regex_selector = "media\" href=\"([^\"]+)"
max_page = 101

[avito.params_flat]
# 623880 Брянск
# 623840 Брянская область
region = "locationId=623880"
# 24 Квартиры
# 25 Дома, дачи, коттеджи
object_category = "categoryId=25"
object_type = "params[499]=5254"
rooms_count = "params[549]=5696"
min_floor = "params[2950][from]=2"
max_floor = "params[2950][to]=2"
page = "p=1"

[avito.params_suburban]
# 623880 Брянск
# 623840 Брянская область
region = "locationId=623840"
# 24 Квартиры
# 25 Дома, дачи, коттеджи
object_category = "categoryId=24"
object_type = "params[556]=5735"
rooms_count = "params[118971]=2308921"
house_floors_count = "params[759]=10903"
page = "p=1"

[cian.params]
region = "region=1"
object_category = "offer_type=flat"
object_type = "object_type=2"
rooms_count = "room=1"
min_floor = "min_floor=2"
max_floor = "max_floor=2"
page = "p=1"
