[avito]
domen_url = "https://www.avito.ru"
url = "https://www.avito.ru/moskva/kvartiry/prodam/do-4-mln-rubley-ASgBAgECAUSSA8YQAUXGmgwXeyJmcm9tIjowLCJ0byI6NDAwMDAwMH0?localPriority=0&p=1"
price_filter_btn_selector = ""
filter_btn_selector = "[data-marker=\"search-filters/submit-button\"]"
next_btn_selector = "[data-marker=\"pagination-button/nextPage\"]"
min_price_selector = "[data-marker=\"price-from/input\"]"
max_price_selector = "[data-marker=\"price-to/input\"]"
offer_urls_selector = "[data-marker=\"catalog-serp\"] [data-marker=\"item-photo-sliderLink\"]"
min_price = 0
max_price = 4000000
price_step = 500000
items_on_page = 50
max_available_page = 1000
p = 19

[cian]
domen_url = "https://www.cian.ru"
url = "https://spb.cian.ru/cat.php?currency=2&deal_type=sale&engine_version=2&maxprice=3500000&offer_type=flat&p=2&region=4588"
price_filter_btn_selector = "[data-testid=\"price\"]"
next_btn_selector = "nav[data-name=\"Pagination\"] > :nth-child(3):is(a)"
min_price_selector = "[placeholder=\"от\"]"
max_price_selector = "[placeholder=\"до\"]"
min_price = 9300001
items_on_page = 28
offer_urls_selector = ".x31de4314--_416c6--media, .x09f03c75--e726a9--content__title > a"
max_price = 10100000
max_available_page = 54
filter_btn_selector = "[data-name=\"SummaryHeader\"], [data-testid=\"listing.offers-count\"]"
price_step = 100000
p = 19
