server {
    listen 80;

    proxy_max_temp_file_size 0; 

    # Проксируем API на FastAPI
    location /apiback/ {
        proxy_pass http://backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Все остальное на Nuxt
    location / {
        proxy_pass http://frontend:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}