// Generated by nuxt-echarts

import type { ComposeOption } from 'echarts/core'
import type {
  BarSeriesOption,
  BoxplotSeriesOption,
  LineSeriesOption,
} from 'echarts/charts'
import type {
  TitleComponentOption,
  GridComponentOption,
  TooltipComponentOption,
  LegendComponentOption,
  DataZoomComponentOption,
} from 'echarts/components'

declare global {
  export type ECOption = ComposeOption<
    | BarSeriesOption
    | BoxplotSeriesOption
    | LineSeriesOption
    | TitleComponentOption
    | GridComponentOption
    | TooltipComponentOption
    | LegendComponentOption
    | DataZoomComponentOption
  >
}

export {}